### ISSUE TITLE
how to prevent restart ?

### ISSUE THREAD

**Issue by zanjibar** [svanzoest-cookbooks/apache2#333]
In my cookbook
first time apache2 restart fail. next time  apache2 work fine.
So how can I prevent first time restart apache2 in middle of provisioning and delay after another
apache2 setting finished.

**Comment by svanzoest** [comment]
Hi @zanjibar 
Do you have any log files of the restart failure that  you can share? I have found that most of the time the failure to restart has to do with a syntax error or an configuration. Also what version of apache2 and on what platform are you using the cookbook on?

**Comment by rcambien** [comment]
Hi !

Same problem here. It started with #305 
I'm running a PHP stack, so I need the prefork MPM.
During the first chef run, the MPM recipe request a delayed Apache restart and the deploy of the PHP apps request delayed Apache reloads.
At the end of the run, chef execute the reload then the restart and I think that Apache don't like the restart during the reload bootstrap.

I don't know what we can do ... maybe by adding a wait before the restart ...

**Comment by svanzoest** [comment]
@rcambien how are you specifying that you need the `prefork` MPM?

**Comment by rcambien** [comment]
I use a role with : 
```ruby
override_attributes(
  :apache => {
    :mpm => "prefork"
  }
)
```

**Comment by phpPhil** [comment]
Same issue here. I've set `mpm => prefork` as @rcambien did. Interesting is there's nothing in stdout and stderr or anything relevant in the apache logs that could indicate what actually went wrong.

These are the logs:

		==> my-server: [2015-05-10T12:05:25+10:00] INFO: execute[a2enmod mpm_prefork] sending restart action to service[apache2] (delayed)
		==> my-server: [2015-05-10T12:05:25+10:00] INFO: Processing service[apache2] action restart (apache2::default line 202)
		==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] supports status, running
		==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] is running
		==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 0, action stop, priority 09
		==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 1, action stop, priority 09
		==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 2, action start, priority 91
		==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 3, action start, priority 91
		==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 4, action start, priority 91
		==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 5, action start, priority 91
		==> my-server: [2015-05-10T12:05:25+10:00] DEBUG: service[apache2] runlevel 6, action stop, priority 09
		==> my-server: ================================================================================
		==> my-server: Error executing action `restart` on resource 'service[apache2]'
		==> my-server: ================================================================================
		==> my-server: Mixlib::ShellOut::ShellCommandFailed
		==> my-server: ------------------------------------
		==> my-server: Expected process to exit with [0], but received '1'
		==> my-server: ---- Begin output of /etc/init.d/apache2 restart ----
		==> my-server: STDOUT: * Restarting web server apache2
		==> my-server:    ...fail!
		==> my-server: STDERR: 
		==> my-server: ---- End output of /etc/init.d/apache2 restart ----
		==> my-server: Ran /etc/init.d/apache2 restart returned 1
		==> my-server: Resource Declaration:
		==> my-server: ---------------------
		==> my-server: # In /tmp/vagrant-chef-2/chef-solo-1/cookbooks/apache2/recipes/default.rb
		==> my-server: 202: service 'apache2' do
		==> my-server: 203:   service_name node['apache']['service_name']
		==> my-server: 204:   case node['platform_family']
		==> my-server: 205:   when 'rhel'
		==> my-server: 206:     reload_command '/sbin/service httpd graceful'
		==> my-server: 207:   when 'debian'
		==> my-server: 208:     provider Chef::Provider::Service::Debian
		==> my-server: 209:   when 'arch'
		==> my-server: 210:     service_name 'httpd'
		==> my-server: 211:   end
		==> my-server: 212:   supports [:start, :restart, :reload, :status]
		==> my-server: Compiled Resource:
		==> my-server: ------------------
		==> my-server: # Declared in /tmp/vagrant-chef-2/chef-solo-1/cookbooks/apache2/recipes/default.rb:202:in `from_file'
		==> my-server: service("apache2") do
		==> my-server:   provider Chef::Provider::Service::Debian
		==> my-server:   action [:enable, :start]
		==> my-server:   updated true
		==> my-server:   supports {:restart=>true, :reload=>true, :status=>true, :start=>true}
		==> my-server:   retries 0
		==> my-server:   retry_delay 2
		==> my-server:   default_guard_interpreter :default
		==> my-server:   service_name "apache2"
		==> my-server:   enabled true
		==> my-server:   running true
		==> my-server:   pattern "apache2"
		==> my-server:   declared_type :service
		==> my-server:   cookbook_name :apache2
		==> my-server:   recipe_name "default"
		==> my-server:   only_if "/usr/sbin/apache2 -t"
		==> my-server: end

Worth noting...
* when I log into the machine after the process aborts, I can restart Apache without any issues.
* this is on AWS, I'm using the Ubuntu AMI `ami-d05e75b8`.

The error stops the provisioning half way through. 
Is there any workaround for this?

**Comment by svanzoest** [comment]
Is apache loaded before your role is in the run list? I have a use case where I am doing this pretty regularly and I am not seeing this.

**Comment by tpetchel** [comment]
I'm seeing the exact same behavior. My use case is a LAMP stack that we're using for a Learn Chef tutorial.

My code is here: https://github.com/learn-chef/manage-a-web-app-ubuntu.

I've observed that the cookbook fails the first time you run it, but the app is configured properly. The second time I run the cookbook, there are no errors, and my app continues to function.

For me, the cookbook runs successfully on a 14.04 EC2 instance, but fails in Test Kitchen/Vagrant.

I've tried both `event` and `prefork` MPM (like @rcambien I'm running PHP, so need to use `prefork`). I get the same behavior in both cases.

Would love to resolve this so I can get unblocked. Thanks!

**Comment by svanzoest** [comment]
@tpetchel I do not see where you are setting `apache.mpm` to `prefork` in your code. I would expect it to be listed at https://github.com/learn-chef/manage-a-web-app-ubuntu/blob/master/chef-repo/cookbooks/awesome_customers/attributes/default.rb#L8

**Comment by tpetchel** [comment]
@svanzoest thanks for looking. Sorry, I should've mentioned that I set `prefork` in my local version. At the exact location you mention, I set it like this:

```
default['apache']['mpm'] = 'prefork'
```

**Comment by svanzoest** [comment]
@tpetchel when it fails, do you see any log output in the apache logs? I suspect that when it fails it is switching between mpms. Does your test-kitchen/vagrant build have apache already installed? Any way you could share the vm and the `.kitchen.yml`?

**Comment by svanzoest** [comment]
Switching between MPM during a chef run is not supported currently, as there are lot of details involved that are very different depending on the platform. Some platforms have the MPM builtin for example, so there is no way to actually do this. We have an open issue for the switching of MPM after install (#236), but I do not expect us to be able to address that any day soon because of the constraints on this issue.

**Comment by tpetchel** [comment]
@svanzoest I'll double check the logs, but from what I remember there wasn't any useful information other than that the restart operation "failed". 

And I'm using the default opscode 14.04 box, which I don't believe comes with Apache installed, but will double check that as well.

Unless I'm misunderstanding, but I don't think there's a MPM switch occurring, since Apache isn't installed yet, `prefork` would be the initial value when it's installed. Plus, I'm able to repo without specifying the MPM, leaving it at the default value of `event`.

**Comment by svanzoest** [comment]
@tpetchel because switching between MPMs is tricky with apache running and already installed, I expect that when you enable `mod_php5` and the current mpm is `event` you will require a second run for you to be able to enable the `prefork` mpm. If you look at the provided [.kitchen.yml](https://github.com/svanzoest-cookbooks/apache2/blob/v3.1.0/.kitchen.yml#L100), it includes `prefork-ubuntu-1404`, which tests this exact scenario and it works okay for me. So, I am trying to understand what is different between what you are doing versus what that is doing.

**Comment by tpetchel** [comment]
@svanzoest your `.kitchen.yml` inspired me to try something. In [webserver.rb](https://github.com/learn-chef/manage-a-web-app-ubuntu/blob/master/chef-repo/cookbooks/awesome_customers/recipes/webserver.rb#L7), I reordered things so that mod_php5 is installed before Apache:

```
# Install the mod_php5 Apache module.
include_recipe 'apache2::mod_php5'
# Install Apache and configure its service.
include_recipe 'apache2::default'
```

and it worked! I naively thought that Apache needed to be installed before this module could be. This feels justifiable to me, but in your opinion, is this an appropriate fix?

**Comment by tpetchel** [comment]
@svanzoest Oh and one more question - I never had problems with this on the [RHEL/CentOS](https://github.com/learn-chef/manage-a-web-app-rhel) version of things, but do you think I should apply the same changes to it as well?

**Comment by svanzoest** [comment]
@tpetchel Hmm..I am not sure I fully understand why changing the order of the install recipe would matter other than now we are forcing ubuntu to pull in `apache2` as a dependency rather than having the cookbook do it first. This suggests to me that your setting of `apache.mpm` did not take. 

We should have [some warning output that mentions what MPM is installed](https://github.com/svanzoest-cookbooks/apache2/blob/v3.1.0/recipes/default.rb#L185-192) and what MPM it is expecting. In `apache2::mod_php5`, we [output similar warnings](https://github.com/svanzoest-cookbooks/apache2/blob/v3.1.0/recipes/mod_php5.rb#L22-26). Are you seeing any of that output?

The `redhat` platform family still only supports `prefork`, so there is no need to change MPMs as the default installed version is what you need for `mod_php5`.

**Comment by tpetchel** [comment]
@svanzoest I think I misread your `.kitchen.yml`. I see now that you are indeed installing Apache before mod_php5. 
I'm continuing to look into it, but what I'm doing looks a whole lot like what you're doing!

And thanks for clearing up my question for `redhat` - that all rings a :bell: now.

**Comment by rcambien** [comment]
Switching recipes also solve my problem ! 
It works because libapache2-mod-php5 have a post-install script that switch the MPM to Prefork : https://github.com/steveathon/Debian-PHP5/blob/master/debian/libapache2-mod-php5.postinst.extra

So, when the default recipe check the MPM, it's already configured.

Switching recipe doesn't solve the problem, we just avoid it ;)

**Comment by tpetchel** [comment]
@svanzoest I've narrowed things down a bit - I started by resetting my cookbook to its initial state, but adding the `prefork` value to my `apache.mvm` attribute. I then removed the database recipe from my run-list. Everything ran fine.  Good so far.

I then added back the database recipe and started commenting resources. Appears that the [mysql_service](https://github.com/learn-chef/manage-a-web-app-ubuntu/blob/master/chef-repo/cookbooks/awesome_customers/recipes/database.rb#L21) resource from the [mysql](https://supermarket.chef.io/cookbooks/mysql) cookbook is what's causing the issue.

What's interesting is that moving the `mod_php5` recipe to the top seems to cover up the problem. Not sure how the interaction with PHP, Apache, and MySQL is causing the Apache service to fail to restart. 

I'll whip up a min repro and see if one of our engineers can help out. But in the meantime, @svanzoest, do you happen to have any insight into what might be happening?

@rcambien are you using `mysql_service` as well by chance?

**Comment by svanzoest** [comment]
@tpetchel Thanks for doing that.  I'd love a repo case. I can't think of anything off the top of my head as to why that would case an issue. @someara any ideas?

**Comment by tpetchel** [comment]
@svanzoest I don't see any warnings. Only warning I've seen but since corrected was the one about PHP wanting to run with prefork.

One update though - a coworker successfully converged my cookbook on the first run, but on a MacOS workstation. I then tried the same thing, but from a Windows workstation, and it also ran clean! 

I then tried converging from a clean Ubuntu 14.04 workstation, and I get the failure (again, only on the first run.) So it appears that this has something to do with the host, which I wouldn't expect. Ubuntu 14.04 so far is the only host I've seen that exhibits the failure. 

I'll check in with some others folks on the team tomorrow to see if anyone has cycles to help investigate.

**Comment by rcambien** [comment]
@tpetchel no, I don't use any mysql cookbook on this run.

Do you think it may be a race condition between the delayed reload and restart ? Chef trying to restart apache immediately after the graceful (or maybe at the same time ?) ?

**Comment by tpetchel** [comment]
@rcambien @svanzoest race condition comes to my mind as well, based on what we've seen.

**Comment by svanzoest** [comment]
Maybe the async nature of upstart/systemd is causing this on busy instances
