### ISSUE TITLE
RHEL Centos 6.x with Apache2.2 reload/restart Timing Failure

### ISSUE THREAD

**Issue by sean-horn** [svanzoest-cookbooks/apache2#342]
There is a timing issue in the RHEL httpd tools/init script that is papered over with the sleeps in the following code before apache2 v2.0.0.
https://github.com/svanzoest-cookbooks/apache2/blob/v1.11.0/recipes/default.rb#L188-L196

The service resource should have these custom commands re-instituted to avoid errors when folks just want to use apache2.2 on older OSes.

**Comment by svanzoest** [comment]
Hi @sean-horn 
Thank you for using the cookbook. Do you have more specifics on the timing issue that you are seeing here? Our goal has been to make sure the cookbook works on most platforms with a deep focus on supporting apache 2.4 on the latest 2 major revisions of an operating system.

It seems to me that this has been fixed in newer versions of the os and package. It is a lot of overhead to keep testing for all the exceptions per platform, so by focusing on the latest major versions we get the most coverage without tons of specially casing and overhead.

Does it make sense for you to just stick with v1.11.0 until you are ready to upgrade?

**Comment by sean-horn** [comment]
@svanzoest The issue is definitely an OS/package issue.

If I do `service httpd reload; service httpd restart` on a centos 6.2 system, then I get

```
[root@localhost ~]# service httpd reload && service httpd restart
Reloading httpd:
Stopping httpd:                                            [  OK  ]
Starting httpd: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain for ServerName
[Mon Apr 06 22:16:16 2015] [warn] NameVirtualHost *:80 has no VirtualHosts
(98)Address already in use: make_sock: could not bind to address [::]:80
(98)Address already in use: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
Unable to open logs
                                                           [FAILED]
[root@localhost ~]# sudo killall /usr/sbin/httpd
[root@localhost ~]# service httpd reload && sleep 1 && service httpd restart
Reloading httpd:                                           [FAILED]
```

If I insert a sleep in there, it succeeds
```
[root@localhost ~]# service httpd reload && sleep 1 && service httpd restart
Reloading httpd:
Stopping httpd:                                            [  OK  ]
Starting httpd: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain for ServerName
[Mon Apr 06 22:09:53 2015] [warn] NameVirtualHost *:80 has no VirtualHosts
                                                           [  OK  ]
```

Yes, that's a good point that the old code handles the issue. Thanks for the update.
I'll close this out.
