### ISSUE TITLE
[Ubuntu] Default recipe installs conflicting mpm_itk.load file

### ISSUE THREAD

**Issue by SIGUSR2** [svanzoest-cookbooks/apache2#351]
Despite not supporting mpm_itk, when using apache 2.4 the default `mpm_*.rb` recipes are calling the apache_module definition for mpm_itk by doing: `apache_module('mpm_itk') { enable false }`. This will create the `/etc/apache2/mods-available/mpm_itk.load` file, which has the wrong content and conflicts with future unattended installations of the `apache2-mpm-itk` package (called by another cookbook). From a shell (after manually installing the `apache2-mpm-itk` package and electing to keep the existing file): 
```
root@host# cat /etc/apache2/mods-available/mpm_itk.load
LoadModule mpm_itk_module /usr/lib/apache2/modules/mod_mpm_itk.so

root@host# ls -la /usr/lib/apache2/modules/mod_mpm_itk.so
ls: cannot access /usr/lib/apache2/modules/mod_mpm_itk.so: No such file or directory

root@host# ls -al /usr/lib/apache2/modules/*itk*
-rw-r--r-- 1 root root 19000 Jan 10  2014 /usr/lib/apache2/modules/mpm_itk.so
```
During the chef-client run, when attempting to call `package 'apache2-mpm-itk'` from a different cookbook, after converging apache2::default , the error is: 
```
Setting up libapache2-mpm-itk (2.4.6-01-1) ...

Configuration file '/etc/apache2/mods-available/mpm_itk.load'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** mpm_itk.load (Y/I/N/O/D/Z) [default=N] ? D
```
and the exit code is 100. 

Tested using v3.0.1 on ubuntu-14.04-x86_64.

**Comment by svanzoest** [comment]
Hi, 

Thanks for your report and using the cookbook. We appreciate it.

We initially had `mpm_itk` support when we released the 2.0 version of the cookbook, but it was not easy enough to support it on all platforms, so we removed it. We decided to focus on the main package as provided by the ASF and any additional modules should be handled by a separate cookbook. It is unfortunate that the `libapache2-mpm-itk` package did not follow the same convention as the `apache2-bin` package for naming mpms, as that seems like it would still make this functionality work.

It might be worth filing an issue with the libapache2-mpm-itk package stating the inconsistency.

Switching between MPMs is still pretty tricky in the cookbook. The best way to do this would be to set `apache.mpm` to 'itk', but since the `apache2::mpm_itk` recipe no longer is included that would not provide the functionality you want.

Do you have any suggestions on how to handle this situation? It seems like removing any notion of itk all together would be good with the ability to not specify an MPM at all during install, or simply do nothing when the `apache.mpm` attribute is set to something that is not supported by the cookbook.

**Comment by SIGUSR2** [comment]
Hello,

I think both your ideas would work, if applied together - maybe with a warning to the user that additional configuration is needed. 

Unfortunately, that's the default behavior of `apt-get` when finding conflicting files pre-created. Even specifying full unattended switches to the command line doesn't work. One needs to play with extra command line options and an environment variable to convince the package manager to overwrite or keep the existing file. 

Thanks.

**Comment by SIGUSR2** [comment]
I've forked and modified the cookbook to work with an unsupported mpm: https://github.com/svanzoest-cookbooks/apache2/compare/master...SIGUSR2:master

Please let me know if that's ok for a PR.

**Comment by svanzoest** [comment]
:+1: Yeah, that looks great. You could then create an `apache2-mpm-itk` cookbook that handles those parts for easy consumption. Thanks!

**Comment by SIGUSR2** [comment]
Allright, PR #353 created. Thank you!

**Comment by svanzoest** [comment]
:+1: merged! Thanks.
