### ISSUE TITLE
How does this cookbook work with php-fpm?

### ISSUE THREAD

**Issue by dolfje** [svanzoest-cookbooks/apache2#395]
I'm trying to get this apache cookbook working with php-fpm, but it is not as easy as hoped.
Shouldn't we introduce apache2::php-fpm as glue between the apache and php install?

So we have this:
```
include_recipe 'apache2::default'
include_recipe 'apache2::mod_fastcgi'
include_recipe 'php'
php_fpm_pool "default" do
  action :install
end
```

But the following, we still have to do manually:
```
sudo nano /etc/apache2/conf-available/php5-fpm.conf
<IfModule mod_fastcgi.c>
AddHandler php5-fcgi .php
Action php5-fcgi /php5-fcgi
Alias /php5-fcgi /usr/lib/cgi-bin/php5-fcgi
FastCgiExternalServer /usr/lib/cgi-bin/php5-fcgi -socket /var/run/php5-fpm.sock -pass-header Authorization

<Directory /usr/lib/cgi-bin>
    Require all granted
</Directory>

</IfModule>
```
```
sudo a2enmod actions fastcgi alias
sudo a2enconf php5-fpm
```

Is this intentional? Or is there another cookbook already doing this? Maybe documentation of this should be welcome. Because the best solution is apache + php fpm, but all documentation (of php) says you need to set the apache mpm to prefork.

**Comment by svanzoest** [comment]
We currently have support for fastcgi via `apache::mod_fastcgi`, you can easily add a configuration file to configure apache to configure fpm. You could also do this in the `web_app` apache virtualhost template.

````
apache_conf 'php5-fpm' do
  enable true
end
````
Since this cookbook focuses directly on the ASF httpd package, it is recommended to use or create a separate cookbook for FPM. There are a few on Supermarket already, maybe [one of them](https://supermarket.chef.io/cookbooks?q=fpm) is suitable to fulfill your needs.
