### ISSUE TITLE
Unable to upload cookbook using Knife

### ISSUE THREAD

**Issue by sernapallyanurag** [svanzoest-cookbooks/apache2#411]
I am able to upload every other cookbook but apache2 upload fails with following error.
I am running my chef-server in Azure (its open source version 11.x)

Uploading apache2 [3.1.0]
ERROR: SSL Validation failure connecting to host: xx.xx.xx.xx - SSL_read: cert already in hash table
ERROR: Could not establish a secure connection to the server.
Use knife ssl check to troubleshoot your SSL configuration.
If your Chef Server uses a self-signed certificate, you can use
knife ssl fetch to make knife trust the server's certificates.

Original Exception: OpenSSL::SSL::SSLError: SSL_read: cert already in hash table

I am unable to understand why specifically for apache2 cookbook.

**Comment by drpebcak** [comment]
This is not a problem with the apache2 cookbook specifically. Take a look at issues like this: https://github.com/chef/chef-dk/issues/492 for more information.

**Comment by svanzoest** [comment]
Good question. I do not see anything specific in the `apache2` cookbook that would cause something like this. The only thing I can think of is because your are using Chef Server 11 and not Chef Server 12, you are hitting #374. You can see if you remove `issues_url` and `source_url` from the `metadata.rb` file and see if that resolves your issue.

Regardless, I would recommend you update to a newer chef server.

**Comment by sernapallyanurag** [comment]
I do not have metadata.rb in my cookbook. there is only metadata.json file.

**Comment by sernapallyanurag** [comment]
--concurrency set to one works.
