### ISSUE TITLE
do not include default for definitions

### ISSUE THREAD

**Issue by xdrus** [svanzoest-cookbooks/apache2#449]
Hello, everyone.

The issue I've met is that if you want to have separate recipe files for base apache configuration and app deploying (where vhost config file is created or updated), apache_site definition includes 'apache::default' (https://github.com/svanzoest-cookbooks/apache2/blob/master/definitions/apache_site.rb#L21). This approach is used at AWS OpsWorks, where you can have different entry points for a server setup and an applications deployment.

Moreover, I can imagine scenarios, when I just want to use those definitions without apache::default (e.g. it was installed with package resource).

So that I think it is better to remove line
```
include_recipe 'apache2::default'
```

from all definition files: apache_conf, apache_config, apache_mod, apache_module, apache_site.

Best regards,
Ruslan.

**Comment by drpebcak** [comment]
Doesn't it kind of go against chef philosophy to only manage portions of an application? Using the apache2 cookbook presupposes you want to manage the entire apache2 application, and I think that is an expected behavior from any community cookbook. Having the cookbook manage everything about the application leads to more consistency and better performance from the cookbook.

Also, the service is created in `default`, so without including that, we wouldn't be able to reload/restart apache. Something like this would cause huge issues.

**Comment by xdrus** [comment]
Thanks, I've got your points, it makes sense, especially about apache service. I'll try to figure out how to deal with it in my case. 

Best regards,
Ruslan.
